version: 2.1
orbs:
  # orgs contain basic recipes and reproducible actions (install node, aws, etc.)
  # triggering update 2
  node: circleci/node@5.0.2
  aws-cli: circleci/aws-cli@1.3.1
  # aws-s3: circleci/aws-s3@3.0.0
  # different jobs are calles later in the workflows sections
jobs:

  # aws-cli-cred-setup:
  #   executor: aws-cli/default
  #   steps:
  #     - aws-cli/setup:
  #         aws-access-key-id: AWS_ACCESS_KEY
  #         aws-secret-access-key: AWS_ACCESS_SECRET
  #         aws-region: AWS_REGION_NAME

  build:
    docker:
      # the base image can run most needed actions with orbs
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - aws-cli/setup
      # install dependencies in both apps
      - run:
          name: front-end install
          command: npm --prefix ./reactnd-contacts-complete/ install

      - run:
          name: back-end install
          command: npm --prefix ./reactnd-contacts-server/ install

      - run:
          name: front-end build
          command: npm --prefix ./reactnd-contacts-complete/ run build

      - run:
          name: back-end build
          command: npm --prefix ./reactnd-contacts-server/ run build

      - run:
          name: front-end deploy
          command: npm --prefix ./reactnd-contacts-complete/ run deploy
