version: 2.1
orbs:
  # orgs contain basic recipes and reproducible actions (install node, aws, etc.)
  # triggering update 2
  node: circleci/node@5.0.2
  aws-cli: circleci/aws-cli@1.3.1
  eb: circleci/aws-elastic-beanstalk@2.0.1
  # aws-s3: circleci/aws-s3@3.0.0
  # different jobs are calles later in the workflows sections
jobs:
  build:
    docker:
      # the base image can run most needed actions with orbs
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - aws-cli/setup
      - eb/setup
      # install dependencies in both apps
      - run:
          name: front-end install
          command: npm --prefix ./udagram-frontend/ install --legacy-peer-deps

      - run:
          name: back-end install
          command: npm --prefix ./udagram-api/ install

      - run:
          name: front-end build
          command: npm --prefix ./udagram-frontend/ run build

      - run:
          name: back-end build
          command: npm --prefix ./udagram-api/ run build

      - run:
          name: front-end deploy
          command: npm --prefix ./udagram-frontend/ run deploy

      - run:
          name: back-end deploy
          command: npm --prefix ./udagram-api/ run deploy

